export interface StockMeta {
  ticker: string;
  name: string;
  market: "KR" | "US";
  sector: string;
}

// ── 국내 종목 (KOSPI/KOSDAQ 시총 상위 + 인기 종목) ─────────────────
export const KR_STOCKS: StockMeta[] = [
  // 반도체/전자
  { ticker: "005930", name: "삼성전자", market: "KR", sector: "semiconductor" },
  { ticker: "000660", name: "SK하이닉스", market: "KR", sector: "semiconductor" },
  { ticker: "009150", name: "삼성전기", market: "KR", sector: "semiconductor" },
  { ticker: "066570", name: "LG전자", market: "KR", sector: "tech" },
  { ticker: "018260", name: "삼성에스디에스", market: "KR", sector: "tech" },
  { ticker: "034220", name: "LG디스플레이", market: "KR", sector: "tech" },
  { ticker: "079550", name: "LIG넥스원", market: "KR", sector: "industrial" },
  { ticker: "042700", name: "한미반도체", market: "KR", sector: "semiconductor" },
  { ticker: "336370", name: "솔브레인홀딩스", market: "KR", sector: "semiconductor" },
  { ticker: "036030", name: "고려제강", market: "KR", sector: "materials" },
  { ticker: "361610", name: "SK아이이테크놀로지", market: "KR", sector: "semiconductor" },
  { ticker: "336830", name: "SK에터닉스", market: "KR", sector: "semiconductor" },
  { ticker: "357780", name: "솔브레인", market: "KR", sector: "semiconductor" },
  { ticker: "058470", name: "리노공업", market: "KR", sector: "semiconductor" },
  { ticker: "240810", name: "원익IPS", market: "KR", sector: "semiconductor" },
  { ticker: "104830", name: "원익머트리얼즈", market: "KR", sector: "semiconductor" },
  { ticker: "039030", name: "이오테크닉스", market: "KR", sector: "semiconductor" },
  { ticker: "102120", name: "어보브반도체", market: "KR", sector: "semiconductor" },
  { ticker: "095910", name: "에스에프에이", market: "KR", sector: "semiconductor" },
  { ticker: "140860", name: "파크시스템스", market: "KR", sector: "semiconductor" },
  { ticker: "403870", name: "HPSP", market: "KR", sector: "semiconductor" },
  { ticker: "131970", name: "두산테스나", market: "KR", sector: "semiconductor" },
  { ticker: "023590", name: "다우기술", market: "KR", sector: "tech" },
  { ticker: "000990", name: "DB하이텍", market: "KR", sector: "semiconductor" },
  // IT/테크
  { ticker: "035420", name: "NAVER", market: "KR", sector: "tech" },
  { ticker: "035720", name: "카카오", market: "KR", sector: "tech" },
  { ticker: "259960", name: "크래프톤", market: "KR", sector: "tech" },
  { ticker: "251270", name: "넷마블", market: "KR", sector: "tech" },
  { ticker: "036570", name: "엔씨소프트", market: "KR", sector: "tech" },
  { ticker: "293490", name: "카카오게임즈", market: "KR", sector: "tech" },
  { ticker: "263750", name: "펄어비스", market: "KR", sector: "tech" },
  { ticker: "078340", name: "컴투스", market: "KR", sector: "tech" },
  { ticker: "069920", name: "카카오뱅크", market: "KR", sector: "finance" },
  { ticker: "377300", name: "카카오페이", market: "KR", sector: "finance" },
  { ticker: "403550", name: "쏘카", market: "KR", sector: "tech" },
  { ticker: "012330", name: "현대모비스", market: "KR", sector: "consumer" },
  // 자동차
  { ticker: "005380", name: "현대차", market: "KR", sector: "consumer" },
  { ticker: "000270", name: "기아", market: "KR", sector: "consumer" },
  { ticker: "003620", name: "KG모빌리티", market: "KR", sector: "consumer" },
  { ticker: "241560", name: "두산밥캣", market: "KR", sector: "industrial" },
  // 배터리/에너지
  { ticker: "373220", name: "LG에너지솔루션", market: "KR", sector: "tech" },
  { ticker: "006400", name: "삼성SDI", market: "KR", sector: "tech" },
  { ticker: "051910", name: "LG화학", market: "KR", sector: "materials" },
  { ticker: "247540", name: "에코프로비엠", market: "KR", sector: "materials" },
  { ticker: "086520", name: "에코프로", market: "KR", sector: "materials" },
  { ticker: "298050", name: "에코프로에이치엔", market: "KR", sector: "materials" },
  { ticker: "096770", name: "SK이노베이션", market: "KR", sector: "energy" },
  { ticker: "010950", name: "S-Oil", market: "KR", sector: "energy" },
  { ticker: "267260", name: "HD현대일렉트릭", market: "KR", sector: "industrial" },
  // 금융
  { ticker: "105560", name: "KB금융", market: "KR", sector: "finance" },
  { ticker: "055550", name: "신한지주", market: "KR", sector: "finance" },
  { ticker: "086790", name: "하나금융지주", market: "KR", sector: "finance" },
  { ticker: "316140", name: "우리금융지주", market: "KR", sector: "finance" },
  { ticker: "032830", name: "삼성생명", market: "KR", sector: "finance" },
  { ticker: "000810", name: "삼성화재", market: "KR", sector: "finance" },
  { ticker: "088350", name: "한화생명", market: "KR", sector: "finance" },
  { ticker: "003490", name: "대한항공", market: "KR", sector: "industrial" },
  { ticker: "138040", name: "메리츠금융지주", market: "KR", sector: "finance" },
  // 헬스케어/바이오
  { ticker: "207940", name: "삼성바이오로직스", market: "KR", sector: "healthcare" },
  { ticker: "068270", name: "셀트리온", market: "KR", sector: "healthcare" },
  { ticker: "000100", name: "유한양행", market: "KR", sector: "healthcare" },
  { ticker: "326030", name: "SK바이오팜", market: "KR", sector: "healthcare" },
  { ticker: "196170", name: "알테오젠", market: "KR", sector: "healthcare" },
  { ticker: "145020", name: "휴젤", market: "KR", sector: "healthcare" },
  { ticker: "302440", name: "SK바이오사이언스", market: "KR", sector: "healthcare" },
  { ticker: "214450", name: "파마리서치", market: "KR", sector: "healthcare" },
  { ticker: "091990", name: "셀트리온헬스케어", market: "KR", sector: "healthcare" },
  { ticker: "128940", name: "한미약품", market: "KR", sector: "healthcare" },
  { ticker: "009420", name: "한올바이오파마", market: "KR", sector: "healthcare" },
  // 소재/화학
  { ticker: "005490", name: "POSCO홀딩스", market: "KR", sector: "materials" },
  { ticker: "010130", name: "고려아연", market: "KR", sector: "materials" },
  { ticker: "011790", name: "SKC", market: "KR", sector: "materials" },
  { ticker: "078600", name: "대주전자재료", market: "KR", sector: "materials" },
  // 방산/항공우주
  { ticker: "012450", name: "한화에어로스페이스", market: "KR", sector: "industrial" },
  { ticker: "047810", name: "한국항공우주", market: "KR", sector: "industrial" },
  { ticker: "064350", name: "현대로템", market: "KR", sector: "industrial" },
  { ticker: "008830", name: "대한항공", market: "KR", sector: "industrial" },
  // 조선/중공업
  { ticker: "009540", name: "HD한국조선해양", market: "KR", sector: "industrial" },
  { ticker: "042660", name: "한화오션", market: "KR", sector: "industrial" },
  { ticker: "010140", name: "삼성중공업", market: "KR", sector: "industrial" },
  { ticker: "267250", name: "HD현대", market: "KR", sector: "industrial" },
  { ticker: "011210", name: "현대위아", market: "KR", sector: "industrial" },
  // 건설/부동산
  { ticker: "006360", name: "GS건설", market: "KR", sector: "industrial" },
  { ticker: "000720", name: "현대건설", market: "KR", sector: "industrial" },
  { ticker: "028260", name: "삼성물산", market: "KR", sector: "industrial" },
  { ticker: "047050", name: "포스코인터내셔널", market: "KR", sector: "industrial" },
  // 통신
  { ticker: "030200", name: "KT", market: "KR", sector: "communication" },
  { ticker: "017670", name: "SK텔레콤", market: "KR", sector: "communication" },
  { ticker: "032640", name: "LG유플러스", market: "KR", sector: "communication" },
  // 엔터/미디어
  { ticker: "352820", name: "하이브", market: "KR", sector: "communication" },
  { ticker: "041510", name: "에스엠", market: "KR", sector: "communication" },
  { ticker: "035900", name: "JYP Ent.", market: "KR", sector: "communication" },
  { ticker: "122870", name: "YG PLUS", market: "KR", sector: "communication" },
  { ticker: "030000", name: "제일기획", market: "KR", sector: "communication" },
  // 유통/소비재
  { ticker: "139480", name: "이마트", market: "KR", sector: "consumer" },
  { ticker: "069960", name: "현대백화점", market: "KR", sector: "consumer" },
  { ticker: "004170", name: "신세계", market: "KR", sector: "consumer" },
  { ticker: "111770", name: "영원무역", market: "KR", sector: "consumer" },
  { ticker: "161390", name: "한국타이어앤테크놀로지", market: "KR", sector: "consumer" },
  // 항공/물류
  { ticker: "011200", name: "HMM", market: "KR", sector: "industrial" },
  { ticker: "086280", name: "현대글로비스", market: "KR", sector: "industrial" },
  { ticker: "003550", name: "LG", market: "KR", sector: "industrial" },
  { ticker: "020560", name: "아시아나항공", market: "KR", sector: "industrial" },
  // ETF
  { ticker: "069500", name: "KODEX 200", market: "KR", sector: "etf" },
  { ticker: "114800", name: "KODEX 인버스", market: "KR", sector: "etf" },
  { ticker: "122630", name: "KODEX 레버리지", market: "KR", sector: "etf" },
  { ticker: "229200", name: "KODEX 코스닥150", market: "KR", sector: "etf" },
  { ticker: "133690", name: "TIGER 미국나스닥100", market: "KR", sector: "etf" },
  { ticker: "360750", name: "TIGER 미국S&P500", market: "KR", sector: "etf" },
];

// ── 해외 종목 (S&P500 + NASDAQ 주요 + 테마주) ─────────────────────
export const US_STOCKS: StockMeta[] = [
  // 빅테크
  { ticker: "AAPL", name: "Apple", market: "US", sector: "tech" },
  { ticker: "MSFT", name: "Microsoft", market: "US", sector: "tech" },
  { ticker: "GOOGL", name: "Alphabet (Google)", market: "US", sector: "tech" },
  { ticker: "GOOG", name: "Alphabet C (Google)", market: "US", sector: "tech" },
  { ticker: "META", name: "Meta Platforms", market: "US", sector: "tech" },
  { ticker: "AMZN", name: "Amazon", market: "US", sector: "tech" },
  { ticker: "NFLX", name: "Netflix", market: "US", sector: "communication" },
  { ticker: "DIS", name: "Disney", market: "US", sector: "communication" },
  { ticker: "SNAP", name: "Snap", market: "US", sector: "communication" },
  { ticker: "TWTR", name: "Twitter/X", market: "US", sector: "communication" },
  { ticker: "PINS", name: "Pinterest", market: "US", sector: "communication" },
  { ticker: "RDDT", name: "Reddit", market: "US", sector: "communication" },
  // AI/반도체
  { ticker: "NVDA", name: "NVIDIA", market: "US", sector: "semiconductor" },
  { ticker: "AMD", name: "AMD", market: "US", sector: "semiconductor" },
  { ticker: "INTC", name: "Intel", market: "US", sector: "semiconductor" },
  { ticker: "QCOM", name: "Qualcomm", market: "US", sector: "semiconductor" },
  { ticker: "AVGO", name: "Broadcom", market: "US", sector: "semiconductor" },
  { ticker: "MU", name: "Micron Technology", market: "US", sector: "semiconductor" },
  { ticker: "AMAT", name: "Applied Materials", market: "US", sector: "semiconductor" },
  { ticker: "LRCX", name: "Lam Research", market: "US", sector: "semiconductor" },
  { ticker: "KLAC", name: "KLA Corporation", market: "US", sector: "semiconductor" },
  { ticker: "ARM", name: "Arm Holdings", market: "US", sector: "semiconductor" },
  { ticker: "SMCI", name: "Super Micro Computer", market: "US", sector: "tech" },
  { ticker: "ASML", name: "ASML", market: "US", sector: "semiconductor" },
  { ticker: "TSM", name: "TSMC", market: "US", sector: "semiconductor" },
  { ticker: "MRVL", name: "Marvell Technology", market: "US", sector: "semiconductor" },
  // 소프트웨어/클라우드
  { ticker: "CRM", name: "Salesforce", market: "US", sector: "tech" },
  { ticker: "ORCL", name: "Oracle", market: "US", sector: "tech" },
  { ticker: "IBM", name: "IBM", market: "US", sector: "tech" },
  { ticker: "ADBE", name: "Adobe", market: "US", sector: "tech" },
  { ticker: "NOW", name: "ServiceNow", market: "US", sector: "tech" },
  { ticker: "WDAY", name: "Workday", market: "US", sector: "tech" },
  { ticker: "TEAM", name: "Atlassian", market: "US", sector: "tech" },
  { ticker: "SNOW", name: "Snowflake", market: "US", sector: "tech" },
  { ticker: "DDOG", name: "Datadog", market: "US", sector: "tech" },
  { ticker: "CRWD", name: "CrowdStrike", market: "US", sector: "tech" },
  { ticker: "ZS", name: "Zscaler", market: "US", sector: "tech" },
  { ticker: "NET", name: "Cloudflare", market: "US", sector: "tech" },
  { ticker: "OKTA", name: "Okta", market: "US", sector: "tech" },
  { ticker: "GTLB", name: "GitLab", market: "US", sector: "tech" },
  { ticker: "HUBS", name: "HubSpot", market: "US", sector: "tech" },
  { ticker: "ZM", name: "Zoom", market: "US", sector: "tech" },
  { ticker: "DOCU", name: "DocuSign", market: "US", sector: "tech" },
  { ticker: "TWLO", name: "Twilio", market: "US", sector: "tech" },
  { ticker: "PATH", name: "UiPath", market: "US", sector: "tech" },
  { ticker: "AI", name: "C3.ai", market: "US", sector: "tech" },
  { ticker: "SOUN", name: "SoundHound AI", market: "US", sector: "tech" },
  { ticker: "BBAI", name: "BigBear.ai", market: "US", sector: "tech" },
  { ticker: "MSFT", name: "Microsoft", market: "US", sector: "tech" },
  // 전기차/모빌리티
  { ticker: "TSLA", name: "Tesla", market: "US", sector: "consumer" },
  { ticker: "RIVN", name: "Rivian", market: "US", sector: "consumer" },
  { ticker: "LCID", name: "Lucid Motors", market: "US", sector: "consumer" },
  { ticker: "NIO", name: "NIO", market: "US", sector: "consumer" },
  { ticker: "LI", name: "Li Auto", market: "US", sector: "consumer" },
  { ticker: "XPEV", name: "XPeng", market: "US", sector: "consumer" },
  { ticker: "F", name: "Ford", market: "US", sector: "consumer" },
  { ticker: "GM", name: "General Motors", market: "US", sector: "consumer" },
  { ticker: "UBER", name: "Uber", market: "US", sector: "tech" },
  { ticker: "LYFT", name: "Lyft", market: "US", sector: "tech" },
  // 금융
  { ticker: "JPM", name: "JPMorgan Chase", market: "US", sector: "finance" },
  { ticker: "BAC", name: "Bank of America", market: "US", sector: "finance" },
  { ticker: "WFC", name: "Wells Fargo", market: "US", sector: "finance" },
  { ticker: "GS", name: "Goldman Sachs", market: "US", sector: "finance" },
  { ticker: "MS", name: "Morgan Stanley", market: "US", sector: "finance" },
  { ticker: "C", name: "Citigroup", market: "US", sector: "finance" },
  { ticker: "BRK.B", name: "Berkshire Hathaway B", market: "US", sector: "finance" },
  { ticker: "BRK.A", name: "Berkshire Hathaway A", market: "US", sector: "finance" },
  { ticker: "V", name: "Visa", market: "US", sector: "finance" },
  { ticker: "MA", name: "Mastercard", market: "US", sector: "finance" },
  { ticker: "AXP", name: "American Express", market: "US", sector: "finance" },
  { ticker: "PYPL", name: "PayPal", market: "US", sector: "finance" },
  { ticker: "COIN", name: "Coinbase", market: "US", sector: "finance" },
  { ticker: "SOFI", name: "SoFi Technologies", market: "US", sector: "finance" },
  { ticker: "SQ", name: "Block (Square)", market: "US", sector: "finance" },
  { ticker: "AFRM", name: "Affirm", market: "US", sector: "finance" },
  { ticker: "HOOD", name: "Robinhood", market: "US", sector: "finance" },
  // 헬스케어
  { ticker: "LLY", name: "Eli Lilly", market: "US", sector: "healthcare" },
  { ticker: "UNH", name: "UnitedHealth", market: "US", sector: "healthcare" },
  { ticker: "JNJ", name: "Johnson & Johnson", market: "US", sector: "healthcare" },
  { ticker: "MRK", name: "Merck", market: "US", sector: "healthcare" },
  { ticker: "ABBV", name: "AbbVie", market: "US", sector: "healthcare" },
  { ticker: "PFE", name: "Pfizer", market: "US", sector: "healthcare" },
  { ticker: "MRNA", name: "Moderna", market: "US", sector: "healthcare" },
  { ticker: "BNTX", name: "BioNTech", market: "US", sector: "healthcare" },
  { ticker: "GILD", name: "Gilead Sciences", market: "US", sector: "healthcare" },
  { ticker: "REGN", name: "Regeneron", market: "US", sector: "healthcare" },
  { ticker: "TMO", name: "Thermo Fisher", market: "US", sector: "healthcare" },
  { ticker: "ABT", name: "Abbott Laboratories", market: "US", sector: "healthcare" },
  { ticker: "CVS", name: "CVS Health", market: "US", sector: "healthcare" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", market: "US", sector: "healthcare" },
  { ticker: "DXCM", name: "DexCom", market: "US", sector: "healthcare" },
  { ticker: "ISRG", name: "Intuitive Surgical", market: "US", sector: "healthcare" },
  // 에너지
  { ticker: "XOM", name: "ExxonMobil", market: "US", sector: "energy" },
  { ticker: "CVX", name: "Chevron", market: "US", sector: "energy" },
  { ticker: "COP", name: "ConocoPhillips", market: "US", sector: "energy" },
  { ticker: "SLB", name: "Schlumberger", market: "US", sector: "energy" },
  { ticker: "OXY", name: "Occidental Petroleum", market: "US", sector: "energy" },
  { ticker: "ENPH", name: "Enphase Energy", market: "US", sector: "energy" },
  { ticker: "FSLR", name: "First Solar", market: "US", sector: "energy" },
  { ticker: "NEE", name: "NextEra Energy", market: "US", sector: "utilities" },
  // 소비재/유통
  { ticker: "AMZN", name: "Amazon", market: "US", sector: "consumer" },
  { ticker: "WMT", name: "Walmart", market: "US", sector: "consumer" },
  { ticker: "COST", name: "Costco", market: "US", sector: "consumer" },
  { ticker: "TGT", name: "Target", market: "US", sector: "consumer" },
  { ticker: "HD", name: "Home Depot", market: "US", sector: "consumer" },
  { ticker: "LOW", name: "Lowe's", market: "US", sector: "consumer" },
  { ticker: "NKE", name: "Nike", market: "US", sector: "consumer" },
  { ticker: "LULU", name: "Lululemon", market: "US", sector: "consumer" },
  { ticker: "SBUX", name: "Starbucks", market: "US", sector: "consumer" },
  { ticker: "MCD", name: "McDonald's", market: "US", sector: "consumer" },
  { ticker: "CMG", name: "Chipotle", market: "US", sector: "consumer" },
  { ticker: "YUM", name: "Yum! Brands", market: "US", sector: "consumer" },
  { ticker: "KO", name: "Coca-Cola", market: "US", sector: "consumer" },
  { ticker: "PEP", name: "PepsiCo", market: "US", sector: "consumer" },
  { ticker: "PG", name: "Procter & Gamble", market: "US", sector: "consumer" },
  { ticker: "SHOP", name: "Shopify", market: "US", sector: "tech" },
  { ticker: "ETSY", name: "Etsy", market: "US", sector: "consumer" },
  // 항공/여행
  { ticker: "DAL", name: "Delta Air Lines", market: "US", sector: "industrial" },
  { ticker: "UAL", name: "United Airlines", market: "US", sector: "industrial" },
  { ticker: "AAL", name: "American Airlines", market: "US", sector: "industrial" },
  { ticker: "LUV", name: "Southwest Airlines", market: "US", sector: "industrial" },
  { ticker: "BKNG", name: "Booking Holdings", market: "US", sector: "consumer" },
  { ticker: "ABNB", name: "Airbnb", market: "US", sector: "consumer" },
  { ticker: "EXPE", name: "Expedia", market: "US", sector: "consumer" },
  // 산업재
  { ticker: "GE", name: "GE Aerospace", market: "US", sector: "industrial" },
  { ticker: "CAT", name: "Caterpillar", market: "US", sector: "industrial" },
  { ticker: "DE", name: "Deere & Company", market: "US", sector: "industrial" },
  { ticker: "HON", name: "Honeywell", market: "US", sector: "industrial" },
  { ticker: "MMM", name: "3M", market: "US", sector: "industrial" },
  { ticker: "UPS", name: "UPS", market: "US", sector: "industrial" },
  { ticker: "FDX", name: "FedEx", market: "US", sector: "industrial" },
  { ticker: "BA", name: "Boeing", market: "US", sector: "industrial" },
  { ticker: "LMT", name: "Lockheed Martin", market: "US", sector: "industrial" },
  { ticker: "RTX", name: "RTX (Raytheon)", market: "US", sector: "industrial" },
  { ticker: "PLTR", name: "Palantir", market: "US", sector: "tech" },
  // 부동산
  { ticker: "AMT", name: "American Tower", market: "US", sector: "real_estate" },
  { ticker: "PLD", name: "Prologis", market: "US", sector: "real_estate" },
  { ticker: "CCI", name: "Crown Castle", market: "US", sector: "real_estate" },
  { ticker: "EQIX", name: "Equinix", market: "US", sector: "real_estate" },
  // 암호화폐/핀테크
  { ticker: "MSTR", name: "MicroStrategy", market: "US", sector: "tech" },
  { ticker: "MARA", name: "Marathon Digital", market: "US", sector: "tech" },
  { ticker: "RIOT", name: "Riot Platforms", market: "US", sector: "tech" },
  { ticker: "CLSK", name: "CleanSpark", market: "US", sector: "tech" },
  // 우주/방산
  { ticker: "SPCE", name: "Virgin Galactic", market: "US", sector: "industrial" },
  { ticker: "RKT", name: "Rocket Companies", market: "US", sector: "finance" },
  { ticker: "RKLB", name: "Rocket Lab", market: "US", sector: "industrial" },
  // 스트리밍/콘텐츠
  { ticker: "SPOT", name: "Spotify", market: "US", sector: "communication" },
  { ticker: "ROKU", name: "Roku", market: "US", sector: "communication" },
  { ticker: "WBD", name: "Warner Bros. Discovery", market: "US", sector: "communication" },
  { ticker: "PARA", name: "Paramount", market: "US", sector: "communication" },
  // ETF
  { ticker: "SPY", name: "SPDR S&P 500 ETF", market: "US", sector: "etf" },
  { ticker: "QQQ", name: "Invesco NASDAQ-100 ETF", market: "US", sector: "etf" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", market: "US", sector: "etf" },
  { ticker: "DIA", name: "SPDR Dow Jones ETF", market: "US", sector: "etf" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", market: "US", sector: "etf" },
  { ticker: "ARKK", name: "ARK Innovation ETF", market: "US", sector: "etf" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", market: "US", sector: "etf" },
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", market: "US", sector: "etf" },
  { ticker: "GLD", name: "SPDR Gold ETF", market: "US", sector: "etf" },
  { ticker: "SLV", name: "iShares Silver ETF", market: "US", sector: "etf" },
  { ticker: "USO", name: "United States Oil ETF", market: "US", sector: "etf" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", market: "US", sector: "etf" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust ETF", market: "US", sector: "etf" },
  { ticker: "BITO", name: "ProShares Bitcoin ETF", market: "US", sector: "etf" },
];

export const ALL_STOCKS = [...KR_STOCKS, ...US_STOCKS];

// 이전 export 이름 호환성 유지
export const KR_POPULAR = KR_STOCKS;
export const US_POPULAR = US_STOCKS;
export const ALL_POPULAR = ALL_STOCKS;

export function searchStocks(query: string, market?: "KR" | "US"): StockMeta[] {
  const list = market ? ALL_STOCKS.filter(s => s.market === market) : ALL_STOCKS;
  if (!query.trim()) return list;
  const q = query.toLowerCase().replace(/\s/g, "");
  const exact: StockMeta[] = [];
  const partial: StockMeta[] = [];
  for (const s of list) {
    const ticker = s.ticker.toLowerCase();
    const name = s.name.toLowerCase().replace(/\s/g, "");
    if (ticker === q || name === q) { exact.push(s); continue; }
    if (ticker.startsWith(q) || name.includes(q)) { partial.push(s); }
  }
  return [...exact, ...partial];
}
